version: "3.2"

services:
  db:
    image: postgres:10.8-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=webpack
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    volumes:
      - .:/usr/src/app
    depends_on:
      - webpack
      - db

  webpack:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/usr/src/app
    ports:
      - "3035:3035"
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
