default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST', '') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>
  username: <%= ENV.fetch('POSTGRES_USER', '') %>
development:
  <<: *default
  database: widgets_development
test:
  <<: *default
  database: widgets_test

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DBNAME', 'widgets_production') %>
